apiVersion: v1
kind: Service
metadata:
   name: dbconfigui-piapp-service
   labels:
     app: dbconfigui-piapp-service
spec:
   type: NodePort
   ports:
     - port: 7777
       #nodePort: 7777
       targetPort: 7777
   selector:
       app: pi-app
       backend: dbinit-service
