apiVersion: v1
kind: Pod
metadata:
  name: pod-with-sidecar
spec:
{{ if .Values.appSandbox.enabled }}
  volumes:
  - name: database-volume 
  - name: myvolume 
    hostPath:
       path: "/home/deeraj/mqtt-auth/db"
       type: DirectoryOrCreate
{{ end }}
    {{- if .Values.customResources.enablespecificdownload }}
    {{- with .Values.nodeSelector }}
       nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- end }}
    {{- with .Values.affinity }}
       affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
       tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}


  
   
  containers:

  # Main application container
  - name: database-service
    imagePullPolicy: IfNotPresent
    image: postgres # alpine is a simple Linux OS image
    network_mode: host
    env:
    - name: "POSTGRES_DB"
      value: "postgres"
    - name: "POSTGRES_USER"
      value: "postgres"
    - name: "POSTGRES_PASSWORD"
      value: "Siemens123"
    volumeMounts:
    - name: database-volume
      mountPath: /var/lib/postgresql
    ports:
    - containerPort: 5432
    
  # Sidecar container
  - name: kpi-service
    imagePullPolicy: IfNotPresent
    image: kpi-image:latest 
    ports:
    - containerPort: 4502
    env:
    - name: "http_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "https_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "no_proxy"
      value: "localhost;127.0.0.1"
    - name: "DBSERVICETYPE"
      value: "postgres"
    - name: "DBSERVICE"
      value: "EdgeDatabase"  
    - name: "EXTENDED_ERRORS"
      value: "true"
    - name: "LOG_DEBUG_INFO"
      value: "true"
    - name: {{ .Values.env.name }}
      value:  '{"postgres":[{"name":"EdgeDatabase","credentials":{"name":"postgres","host":"localhost","port":"5432","username":"postgres","password":"Siemens123"}}]}'

  - name: asset-service
    imagePullPolicy: IfNotPresent
    image: asset-image:latest     
    ports:
    - containerPort: 4504
    env:
    - name: "http_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "https_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "no_proxy"
      value: "localhost;127.0.0.1"
    - name: "DBSERVICETYPE"
      value: "postgres"
    - name: "DBSERVICE"
      value: "EdgeDatabase"  
    - name: "EXTENDED_ERRORS"
      value: "true"
    - name: "LOG_DEBUG_INFO"
      value: "true"
    - name: {{ .Values.env.name }}
      value:  '{"postgres":[{"name":"EdgeDatabase","credentials":{"name":"postgres","host":"localhost","port":"5432","username":"postgres","password":"Siemens123"}}]}'
      
  - name: data-service
    imagePullPolicy: IfNotPresent
    image: data-image:latest  
    
    ports:
    - containerPort: 4505
    env:
    - name: "http_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "https_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "no_proxy"
      value: "localhost;127.0.0.1"
    - name: "DBSERVICETYPE"
      value: "postgres"
    - name: "DBSERVICE"
      value: "EdgeDatabase"  
    - name: "EXTENDED_ERRORS"
      value: "true"
    - name: "LOG_DEBUG_INFO"
      value: "true"
    - name: {{ .Values.env.name }}
      value: '{"postgres":[{"name":"EdgeDatabase","credentials":{"name":"postgres","host":"localhost","port":"5432","username":"postgres","password":"Siemens123"}}]}'
  - name: dashboard-service
    imagePullPolicy: IfNotPresent
    image: dashboard-image:latest  
    
    ports:
    - containerPort: 4506
    env:
    - name: "http_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "https_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "no_proxy"
      value: "localhost;127.0.0.1"
    - name: "DBSERVICETYPE"
      value: "postgres"
    - name: "DBSERVICE"
      value: "EdgeDatabase"  
    - name: "EXTENDED_ERRORS"
      value: "true"
    - name: "LOG_DEBUG_INFO"
      value: "true"
    - name: {{ .Values.env.name }}
      value: '{"postgres":[{"name":"EdgeDatabase","credentials":{"name":"postgres","host":"localhost","port":"5432","username":"postgres","password":"Siemens123"}}]}'

  - name: usermanager-service
    imagePullPolicy: IfNotPresent
    image: usermanager-image:latest  
    
    ports:
    - containerPort: 4507
    env:
    - name: "http_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "https_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "no_proxy"
      value: "localhost;127.0.0.1"
    - name: "DBSERVICETYPE"
      value: "postgres"
    - name: "DBSERVICE"
      value: "EdgeDatabase"  
    - name: "EXTENDED_ERRORS"
      value: "true"
    - name: "LOG_DEBUG_INFO"
      value: "true"
    - name: {{ .Values.env.name }}
      value: '{"postgres":[{"name":"EdgeDatabase","credentials":{"name":"postgres","host":"localhost","port":"5432","username":"postgres","password":"Siemens123"}}]}' 
  
  - name: billing-service
    imagePullPolicy: IfNotPresent
    image: billing-image:latest  
    
    ports:
    - containerPort: 4508
    env:
    - name: "http_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "https_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "no_proxy"
      value: "localhost;127.0.0.1"
    - name: "DBSERVICETYPE"
      value: "postgres"
    - name: "DBSERVICE"
      value: "EdgeDatabase"  
    - name: "EXTENDED_ERRORS"
      value: "true"
    - name: "LOG_DEBUG_INFO"
      value: "true"
    - name: {{ .Values.env.name }}
      value: '{"postgres":[{"name":"EdgeDatabase","credentials":{"name":"postgres","host":"localhost","port":"5432","username":"postgres","password":"Siemens123"}}]}' 

  - name: time-service
    imagePullPolicy: IfNotPresent
    image: time-image:latest  
    
    ports:
    - containerPort: 4509
    env:
    - name: "http_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "https_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "no_proxy"
      value: "localhost;127.0.0.1"
    - name: "DBSERVICETYPE"
      value: "postgres"
    - name: "DBSERVICE"
      value: "EdgeDatabase"  
    - name: "EXTENDED_ERRORS"
      value: "true"
    - name: "LOG_DEBUG_INFO"
      value: "true"
    - name: {{ .Values.env.name }}
      value: '{"postgres":[{"name":"EdgeDatabase","credentials":{"name":"postgres","host":"localhost","port":"5432","username":"postgres","password":"Siemens123"}}]}' 
      
  - name: test-service
    imagePullPolicy: IfNotPresent
    image: test-image:latest  
    
    ports:
    - containerPort: 45011
    env:
    - name: "http_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "https_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "no_proxy"
      value: "localhost;127.0.0.1"
    - name: "DBSERVICETYPE"
      value: "postgres"
    - name: "DBSERVICE"
      value: "EdgeDatabase"  
    - name: "EXTENDED_ERRORS"
      value: "true"
    - name: "LOG_DEBUG_INFO"
      value: "true"
    - name: {{ .Values.env.name }}
      value: '{"postgres":[{"name":"EdgeDatabase","credentials":{"name":"postgres","host":"localhost","port":"5432","username":"postgres","password":"Siemens123"}}]}'

  - name: frontend-service
    imagePullPolicy: IfNotPresent
    image: frontend-image:latest  
    
    ports:
    - containerPort: 4201
    env:
    - name: "http_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "https_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "no_proxy"
      value: "localhost;127.0.0.1"
    - name: "DBSERVICETYPE"
      value: "postgres"
    - name: "DBSERVICE"
      value: "EdgeDatabase"  
    - name: "EXTENDED_ERRORS"
      value: "true"
    - name: "LOG_DEBUG_INFO"
      value: "true"
    - name: {{ .Values.env.name }}
      value: '{"postgres":[{"name":"EdgeDatabase","credentials":{"name":"postgres","host":"localhost","port":"5432","username":"postgres","password":"Siemens123"}}]}'

  - name: dbinit-service
    imagePullPolicy: IfNotPresent
    image: dbinitapi-image:latest  
    network_mode: host
    ports:
    - containerPort: 1337
    env:
    - name: "http_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "https_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "no_proxy"
      value: "localhost;127.0.0.1"
    - name: "DBSERVICETYPE"
      value: "postgres"
    - name: "DBSERVICE"
      value: "EdgeDatabase"  
    - name: "EXTENDED_ERRORS"
      value: "true"
    - name: "LOG_DEBUG_INFO"
      value: "true"
    - name: {{ .Values.env.name }}
      value: '{"postgres":[{"name":"EdgeDatabase","credentials":{"name":"postgres","host":"localhost","port":"5432","username":"postgres","password":"Siemens123"}}]}'

  - name: publisher-service
    imagePullPolicy: IfNotPresent
    image: demo_publisher:latest  
    
    ports:
    - containerPort: 3500
    env:
    - name: "http_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "https_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "no_proxy"
      value: "localhost;127.0.0.1"
    - name: "DBSERVICETYPE"
      value: "postgres"
    - name: "DBSERVICE"
      value: "EdgeDatabase"  
    - name: "EXTENDED_ERRORS"
      value: "true"
    - name: "LOG_DEBUG_INFO"
      value: "true"
    - name: {{ .Values.env.name }}
      value: '{"postgres":[{"name":"EdgeDatabase","credentials":{"name":"postgres","host":"localhost","port":"5432","username":"postgres","password":"Siemens123"}}]}'

  - name: subscriber-service
    imagePullPolicy: IfNotPresent
    image: demo_subscriber:latest  
    
    ports:
    - containerPort: 3000
    env:
    - name: "http_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "https_proxy"
      value: 'http://194.138.0.25:9400'
    - name: "no_proxy"
      value: "localhost;127.0.0.1"
    - name: "DBSERVICETYPE"
      value: "postgres"
    - name: "DBSERVICE"
      value: "EdgeDatabase"  
    - name: "EXTENDED_ERRORS"
      value: "true"
    - name: "LOG_DEBUG_INFO"
      value: "true"
    - name: {{ .Values.env.name }}
      value: '{"postgres":[{"name":"EdgeDatabase","credentials":{"name":"postgres","host":"localhost","port":"5432","username":"postgres","password":"Siemens123"}}]}'      
  
  - name: mqtt-service
    imagePullPolicy: IfNotPresent
    image: siemens/sim-edge-app-mosquitto-broker:0.1.4.6.65 
    ports:
    - containerPort: 1883
      name: https
      protocol: TCP
    - containerPort: 1884
      name: iowa
      protocol: TCP
    {{ if .Values.appSandbox.enabled }}
    volumeMounts:
    - name: myvolume 
      mountPath: /home/mosquitto/data
      {{- end }}
      resources:
{{ toYaml .Values.resources | indent 12 }}
  
  - name: dbconfigui-service
    imagePullPolicy: IfNotPresent
    image: dbconfig-ui:latest     
    ports:
    - containerPort: 7777
    network_mode: host
      
    
  
  
